CREATE DATABASE IF NOT EXISTS Wallet_Watcher;
USE Wallet_Watcher;
CREATE TABLE IF NOT EXISTS Transactions (Name VARCHAR(100), Amount DECIMAL(10,2), Category VARCHAR(100), Date DATE, Id INT AUTO_INCREMENT, PRIMARY KEY (Id));
CREATE TABLE IF NOT EXISTS Categories (Name VARCHAR(100), Amount DECIMAL(10,2), Id INT AUTO_INCREMENT, PRIMARY KEY (Id));
CREATE TABLE IF NOT EXISTS Rules (Category VARCHAR(100), Operator VARCHAR(100), Target VARCHAR(100), Id INT AUTO_INCREMENT, PRIMARY KEY (Id));
